### ISSUE TITLE
提点小建议

### ISSUE THREAD

**Issue by Vanessa219** [pengljun/solo-aragaki#1]
- [x] 我的开源、归档、搜索，鼠标移上去时消失了
- [x] 日期和日期图标中间需要一个空格
- [x] .pagination 样式添加：`border-top: 1px solid #eee;`
- [x] rss 和开始使用中间可以加个空格或分隔符
- [x] .footer > .ft__center > .user__site 可以添加样式：`display: inline-block;margin: 0 10px;`
- [x] `.article-list article:last-child .meta { border-bottom-width: 0}`
- [x] http://blog.konngo.cn/archives 中文章归档前面来个 `<br>`

非常感谢你的分享，欢迎[加入](https://hacpai.com/article/1493814851007#toc_h2_18)

**Comment by ljunn** [comment]
谢谢 ，已经修改了。
